Repository GSG-G11/Bazzar, pull requests merged in 2022-02, with the labels that each got.

#22 4 file structure
  .gitignore
  README.md
  actions.js
  buyer-cart/buyer-cart.html
  buyer-cart/main.js
  buyer-cart/style.css
  buyer-dashboard/buyer-dashboard.html
  buyer-dashboard/main.js
  buyer-dashboard/style.css
  index.html
  main.js
  package-lock.json
  package.json
  seller-add-product/main.js
  seller-add-product/seller-dashboard.html
  seller-add-product/style.css
  seller-dashboard/main.js
  seller-dashboard/seller-dashboard.html
  seller-dashboard/style.css
  style.css
  test.js
Labels: Awaiting Review

#23 design home page
  index.html
  style.css
Labels: Done

#26 create CSS and html files
  buyer-dashboard/buyer-dashboard.html
  buyer-dashboard/style.css
Labels: Awaiting Review

#27 add Dom file
  buyer-cart/main.js
  buyer-dashboard/style.css
Labels: Awaiting Review

#29 create html, css code for cart page
  buyer-cart/buyer-cart.html
  buyer-cart/main.js
  buyer-cart/style.css
  buyer-dashboard/main.js
Labels: Awaiting Review

#30 Revert "create html, css code for cart page"
  buyer-cart/buyer-cart.html
  buyer-cart/main.js
  buyer-cart/style.css
  buyer-dashboard/main.js
Labels: Awaiting Review

#31 add Dom for display cart
  buyer-dashboard/main.js
Labels: Awaiting Review

#34 add links
  index.html
Labels: Approved

#36 create function
  buyer-cart/main.js
Labels: Awaiting Review

#38 add delete button
  buyer-cart/buyer-cart.html
  buyer-cart/main.js
  buyer-cart/style.css
  buyer-dashboard/buyer-dashboard.html
Labels: Awaiting Review

#40 add Dom in cart page
  buyer-cart/main.js
  index.html
Labels: Approved

#42 Add animation to home page
  style.css
Labels: Awaiting Review

#43 Creat total price in cart page using html css and js
  buyer-cart/buyer-cart.html
  buyer-cart/main.js
  buyer-cart/style.css
Labels: Approved

#44 add filter search
   buyer-dashboard/buyer-dashboard.html
   buyer-dashboard/main.js
   buyer-dashboard/style.css
  actions.js
  buyer-dashboard/main.js
  package-lock.json
  test.js
Labels: Awaiting Review

#32 18 add new product
  seller-add-product/main.js
  seller-add-product/seller-add-product.html
  seller-add-product/seller-dashboard.html
  seller-add-product/style.css
Labels: Awaiting Review

#46 Fix Add Product Page Design
  seller-add-product/style.css
Labels: Awaiting Review

#48 Fix links And Desgin of buyer Page
   buyer-dashboard/style.css
  buyer-cart/buyer-cart.html
  buyer-cart/main.js
  buyer-cart/style.css
  index.html
Labels: Awaiting Review

#49 19 seller pages
  actions.js
  seller-add-product/main.js
  seller-add-product/seller-add-product.html
  seller-dashboard/main.js
  seller-dashboard/seller-dashboard.html
  seller-dashboard/style.css
  test.js
Labels: Awaiting Review

#50 Fix Desgin Seller Product Card
  seller-dashboard/style.css
Labels: Awaiting Review

#53 add test
  actions.js
  buyer-cart/main.js
  test.js
Labels: Awaiting Review

#57 Add Test Of TotalPrice
  actions.js
  package-lock.json
  seller-dashboard/seller-dashboard.html
  seller-dashboard/style.css
  test.js
Labels: Approved

#58 load tobe edit data
  seller-add-product/main.js
Labels: Awaiting Review

#59 fix readme
  README.md
Labels: Approved

#72 convert let to const
  actions.js
Labels: Awaiting Review

#73 65 total price bug fix
  buyer-cart/main.js
Labels: Awaiting Review
